// Tests for src/js/lifehash.js using Node's built-in test runner.
//
// The module is a browser IIFE that renders LifeHash (version2) icons as PNG
// data URLs. These tests evaluate it with WebCrypto and a btoa shim, then
// check the rendered image against reference vectors generated by the
// canonical `lifehash` JS package (AndreasGassmann/lifehash), plus PNG
// structure and the presentation rules.
//
// Run with `npm test` (part of the suite) or `node --test test/lifehash.test.mjs`.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createHash, webcrypto } from "node:crypto";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const src = readFileSync(join(root, "src/js/lifehash.js"), "utf8");

// Evaluate the IIFE with the browser globals it expects.
const load = () => {
  const btoa = (s) => Buffer.from(s, "binary").toString("base64");
  const factory = new Function("crypto", "btoa", "TextEncoder", `${src}; return hodlLifeHash;`);
  return factory(webcrypto, btoa, TextEncoder);
};

const sha256Hex = (bytes) => createHash("sha256").update(Buffer.from(bytes)).digest("hex");

// Reference vectors: SHA-256 of the raw 32x32 RGB pixels produced by the
// canonical lifehash JS implementation (version2, module_size 1) for the
// fingerprint string. Generated once and pinned here as a regression oracle.
const VECTORS = [
  { input: "73c5da0a", rgb: "094d645318061f009f3d60aa1f196d9ed59868f2407d78d69c0772c02cdd21c8" },
  { input: "00000000", rgb: "9cae40ba1272c23df266c71dc2535bf97a033f0e7d04d46b5b538f1b3345365c" },
  { input: "ffffffff", rgb: "77a2d1c510c4e173e4ee1b2531dec918e40d0790c7ffb78f964a38b882cc518a" },
  { input: "b8688df1", rgb: "bd129ec7b61d576013ca2c5a0c242f3ffcd1f9c33ad2e32510200122d339df8a" },
];

const renderRgb = async (lifehash, text) => {
  const digest = new Uint8Array(await webcrypto.subtle.digest("SHA-256", new TextEncoder().encode(text)));
  const { runGameOfLife, buildFracGrid, selectGradient, renderColors, makeBitEnumerator } = lifehash._internals;
  const history = await runGameOfLife(digest);
  const entropy = makeBitEnumerator(digest);
  entropy.next();
  entropy.next();
  const gradient = selectGradient(entropy);
  const snowflake = entropy.next();
  const frac = buildFracGrid(history);
  return renderColors(frac, gradient, snowflake);
};

test("rendered 32x32 RGB matches the canonical LifeHash vectors", async () => {
  const lifehash = load();
  for (const { input, rgb } of VECTORS) {
    const { width, height, data } = await renderRgb(lifehash, input);
    assert.equal(width, 32, input);
    assert.equal(height, 32, input);
    assert.equal(data.length, 32 * 32 * 3, input);
    assert.equal(sha256Hex(data), rgb, `LifeHash mismatch for ${input}`);
  }
});

test("fromFingerprint returns a well-formed PNG data URL", async () => {
  const lifehash = load();
  const url = await lifehash.fromFingerprint("73c5da0a", 3);
  assert.match(url, /^data:image\/png;base64,/);
  const png = Buffer.from(url.split(",")[1], "base64");
  assert.deepEqual([...png.subarray(0, 8)], [137, 80, 78, 71, 13, 10, 26, 10], "PNG signature");
  // IHDR: 32x32 source at moduleSize 3 -> 96x96, 8-bit truecolour.
  assert.equal(png.readUInt32BE(16), 96, "width");
  assert.equal(png.readUInt32BE(20), 96, "height");
  assert.equal(png[24], 8, "bit depth");
  assert.equal(png[25], 2, "colour type");
});

test("fingerprint input is normalised to lowercase before hashing", async () => {
  const lifehash = load();
  const lower = await lifehash.fromFingerprint("73c5da0a");
  const upper = await lifehash.fromFingerprint("73C5DA0A");
  assert.equal(lower, upper);
});

test("distinct fingerprints produce distinct images", async () => {
  const lifehash = load();
  const a = await lifehash.fromFingerprint("73c5da0a");
  const b = await lifehash.fromFingerprint("b8688df1");
  assert.notEqual(a, b);
});

test("fromFingerprint is deterministic across runs", async () => {
  const lifehash = load();
  const first = await lifehash.fromFingerprint("73c5da0a");
  const second = await lifehash.fromFingerprint("73c5da0a");
  assert.equal(first, second);
});

test("fromDigest rejects a non-32-byte digest", async () => {
  const lifehash = load();
  await assert.rejects(() => lifehash.fromDigest(new Uint8Array(16)), /32 bytes/);
});
