// Verifies the freshly built site artifact: the compiled entropylab.html and
// the published assets. The artifact is generated by `npm run build` (CI
// builds it before running this); it is not committed.
// Zero dependencies. Run with `npm run verify`.
import {
  existsSync,
  lstatSync,
  readdirSync,
  readFileSync,
  statSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const fail = (message) => {
  console.error(message);
  process.exit(1);
};

const repoDir = dirname(dirname(fileURLToPath(import.meta.url)));
const pkg = JSON.parse(readFileSync(join(repoDir, "package.json"), "utf8"));
const version = pkg.version;

if (!/^\d+(?:\.\d+)*$/.test(version)) {
  fail(`Invalid version in package.json: ${version}`);
}
const appFile = "entropylab.html";

for (const name of [appFile, "assets/favicon.png", "assets/entropylab_dark.png"]) {
  const path = join(repoDir, name);
  if (!existsSync(path) || statSync(path).size === 0) {
    fail(`Site artifact is missing or empty: ${name}\nRun 'npm run build' first.`);
  }
}

// No stale versioned snapshots at the repository root.
const rootSnapshots = readdirSync(repoDir).filter((name) => /^entropylab-\d+(?:\.\d+)*\.html$/.test(name));
if (rootSnapshots.length !== 0) {
  fail(`Unexpected versioned snapshots at the root: ${rootSnapshots.join(", ")}`);
}

// Published assets must be intact and free of symbolic links.
const walk = (dir, prefix) => {
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    const label = join(prefix, name);
    const stats = lstatSync(path);
    if (stats.isSymbolicLink()) fail(`Symbolic link in published assets: ${label}`);
    if (stats.isDirectory()) {
      walk(path, label);
    } else if (stats.size === 0) {
      fail(`Empty published asset: ${label}`);
    }
  }
};
walk(join(repoDir, "assets"), "assets");

console.log(`Verified site artifact for v${version} (${appFile}, assets/).`);
